version: "3.7"

services:
  app:
    build: .
    ports:
      - 50051:50051
    environment:
      CALCULATOR_ENV: dev
      CALCULATOR_RATE_LIMIT_DURATION: 1s
      CALCULATOR_MONTHS_IN_A_YEAR: 12
      CALCULATOR_MIN_YEAR_TO_RESIDE: 1
      CALCULATOR_MIN_MORTGAGE_TERM: 0
      CALCULATOR_MAX_MORTGAGE_TERM: 0
